export const ACTION_TYPE = {
	APP: {
		LOADING: 'APP/LOADING',
	},
	USER: {
		SET_USER: 'USER/SET_USER',
		LOG_OUT: 'USER/LOG_OUT',
	},
	USERS: {
		SET_USERS: 'USERS/SET_USERS',
		DELETE_USER: 'USERS/DELETE_USER',
	},
	ROLES: {
		SET_ROLES: 'ROLES/SET_ROLES',
	},
	POST: {
		SET_POST: 'POST/SET_POST',
		ADD_COMMENT: 'POST/ADD_COMMENT',
		DELETE_COMMENT: 'POST/DELETE_COMMENT',
	},
};
