export const ACTION_TYPE = {
	APP: {
		LOADING: 'APP/LOADING',
		CLOSE_MODAL: 'APP/CLOSE_MODAL',
		OPEN_MODAL: 'APP/OPEN_MODAL',
	},
	USER: {
		SET_USER: 'USER/SET_USER',
		LOG_OUT: 'USER/LOG_OUT',
	},
	USERS: {
		SET_USERS: 'USERS/SET_USERS',
		DELETE_USER: 'USERS/DELETE_USER',
	},
	POST: {
		SET_POST: 'POST/SET_POST',
		ADD_COMMENT: 'POST/ADD_COMMENT',
		DELETE_COMMENT: 'POST/DELETE_COMMENT',
		UPDATE: 'POST/UPDATE',
		DELETE: 'POST/DELETE',
		CLEAR_POST: 'POST/CLEAR_POST',
	},
	POSTS: {
		DELETE_POST: 'POSTS/DELETE_POST',
		SET_POSTS: 'POSTS/SET_POSTS',
	},
};
